# Generated by Django 3.0.4 on 2020-04-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='martphone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('price', models.FloatField(max_length=4)),
                ('discount', models.IntegerField()),
                ('category', models.CharField(max_length=15)),
                ('image_link', models.CharField(max_length=150)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
