# Generated by Django 3.0.4 on 2020-04-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='martphone',
            new_name='shop',
        ),
    ]
