# Generated by Django 3.0.5 on 2020-04-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200407_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shop',
        ),
    ]
