# Generated by Django 3.0.5 on 2020-04-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_company_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='category',
        ),
    ]
